### ISSUE TITLE
Crash when starting app [1h-2h]

### ISSUE THREAD

**Issue by tuancoltech** [elimu-ai/appstore#123]
ClassCastException

Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
                                                                             at android.app.SharedPreferencesImpl.getLong(SharedPreferencesImpl.java:249)
                                                                             at ai.elimu.appstore.MainActivity.onStart(MainActivity.java:94)

**Comment by jo-elimuai** [comment]
What are the steps for reproducing this error? Was the problem fixed?

**Comment by tuancoltech** [comment]
It's actually a false alarm, Jo.
In installed new APK without removing old APK, so there was shared preferences conflict.
We can close this issue.
