### ISSUE TITLE
Compare checksum after download [3-5d]

### ISSUE THREAD

**Issue by jo-elimuai** [elimu-ai/appstore#135]
Store files being downloaded in a temporary folder separate from the Appstore folder.

Do _not_ store a downloaded APK file in the Appstore folder until its checksum has been validated.

Depends on https://github.com/elimu-ai/webapp/issues/616

**Comment by jo-elimuai** [comment]
See https://stackoverflow.com/questions/13152736/how-to-generate-an-md5-checksum-for-a-file-in-android/14922433#14922433

**Comment by jo-elimuai** [comment]
Suggestion: Delete all files under `/sdcard/.elimu-ai/appstore/apks/en/` so that @bvalbo won't have to manually delete corrupt files before upgrading to version 2.0.9 of the Appstore application. Add this code to BaseApplication#onCreate, inside `if (newVersionCode < 2000009) { ... }`

**Comment by jo-elimuai** [comment]
Relates to #62

**Comment by jo-elimuai** [comment]
Crashed when upgrading from 2.0.10 to 2.0.11:

```
01-22 00:22:25.069 22100-22100/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: ai.elimu.appstore, PID: 22100
                                                   android.database.sqlite.SQLiteException: no such column: T.CHECKSUM_MD5 (code 1): , while compiling: SELECT T."_id",T."APPLICATION_ID",T."FILE_SIZE_IN_KB",T."FILE_URL",T."CONTENT_TYPE",T."VERSION_CODE",T."START_COMMAND",T."TIME_UPLOADED",T."CHECKSUM_MD5" FROM "APPLICATION_VERSION" T WHERE T."_id"=?
                                                       at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                       at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:889)
                                                       at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:500)
                                                       at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                       at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                       at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                       at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                       at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                       at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1255)
                                                       at org.greenrobot.greendao.database.StandardDatabase.rawQuery(StandardDatabase.java:32)
                                                       at org.greenrobot.greendao.AbstractDao.load(AbstractDao.java:147)
                                                       at ai.elimu.appstore.synchronization.AppSynchronizationActivity.processAppListData(AppSynchronizationActivity.java:235)
                                                       at ai.elimu.appstore.synchronization.AppSynchronizationActivity.access$300(AppSynchronizationActivity.java:50)
                                                       at ai.elimu.appstore.synchronization.AppSynchronizationActivity$1$1.onResponse(AppSynchronizationActivity.java:137)
                                                       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5268)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
```

I'll implement a fix, and release version 2.0.12

**Comment by jo-elimuai** [comment]
Update: Do not check the checksum while scrolling the list. Instead, only perform this computational heavy operation after a file download completes. If the checksum matches, move the file from the temporary folder to the correct location.

**Comment by jo-elimuai** [comment]
Only use File.exists when checking if an APK file has been downloaded. Do not calculate its size. This to reduce computation while scrolling the list of apps.

**Comment by jo-elimuai** [comment]
Corrupted APK file can be reproduced by for example killing the app before completing a download, or rebooting the tablet, etc.

I suggest storing an APK file being downloaded in a separate temporary location. And once a downloaded file has been verified, it can be moved to the destination folder.
