### ISSUE TITLE
Fix OutOfMemoryError when downloading large files [4-8d]

### ISSUE THREAD

**Issue by jo-elimuai** [elimu-ai/appstore#147]
The application crashes when reaching ~120MB downloaded:

```
01-13 15:09:26.150 15822-15933/ai.elimu.appstore.debug E/art: Throwing OutOfMemoryError "Failed to allocate a 134217740 byte allocation with 16777216 free bytes and 123MB until OOM"
01-13 15:09:26.177 15822-15933/ai.elimu.appstore.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
                                                                         Process: ai.elimu.appstore.debug, PID: 15822
                                                                         java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                             at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                                             at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                             at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                             at java.lang.Thread.run(Thread.java:818)
                                                                          Caused by: java.lang.OutOfMemoryError: Failed to allocate a 134217740 byte allocation with 16777216 free bytes and 123MB until OOM
                                                                             at org.apache.commons.io.output.ByteArrayOutputStream.needNewBuffer(ByteArrayOutputStream.java:127)
                                                                             at org.apache.commons.io.output.ByteArrayOutputStream.write(ByteArrayOutputStream.java:158)
                                                                             at ai.elimu.appstore.synchronization.DownloadApplicationAsyncTask.doInBackground(DownloadApplicationAsyncTask.java:167)
                                                                             at ai.elimu.appstore.synchronization.DownloadApplicationAsyncTask.doInBackground(DownloadApplicationAsyncTask.java:39)
                                                                             at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                             at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                             at java.lang.Thread.run(Thread.java:818) 
```

**Comment by jo-elimuai** [comment]
This only seems to happen on devices with less than 2GB RAM

**Comment by jo-elimuai** [comment]
Another example on Lenovo TB2-X30F (1GB RAM):

```
01-24 23:22:29.291 13705-13899/? E/art: Throwing OutOfMemoryError "Failed to allocate a 134217740 byte allocation with 16777120 free bytes and 125MB until OOM"
01-24 23:22:29.419 13705-13899/? E/art: Throwing OutOfMemoryError "Failed to allocate a 134217740 byte allocation with 16777216 free bytes and 125MB until OOM"
                                        
                                        [ 01-24 23:22:29.432 13705:13899 W/         ]
                                        Invalid checksum. Deleting downloaded APK file: /storage/emulated/0/.elimu-ai/appstore/apks/en/com.alphabetking.story.level_b-300.apk
01-24 23:22:29.552 13705-13899/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
                                                   Process: ai.elimu.appstore, PID: 13705
                                                   java.lang.RuntimeException: An error occured while executing doInBackground()
                                                       at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                    Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                       at android.os.Handler.<init>(Handler.java:200)
                                                       at android.os.Handler.<init>(Handler.java:114)
                                                       at android.widget.Toast$TN.<init>(Toast.java:344)
                                                       at android.widget.Toast.<init>(Toast.java:100)
                                                       at android.widget.Toast.makeText(Toast.java:258)
                                                       at ai.elimu.appstore.synchronization.DownloadApplicationAsyncTask.doInBackground(DownloadApplicationAsyncTask.java:202)
                                                       at ai.elimu.appstore.synchronization.DownloadApplicationAsyncTask.doInBackground(DownloadApplicationAsyncTask.java:39)
                                                       at android.os.AsyncTask$2.call(AsyncTask.java:292)
```

**Comment by tuancoltech** [comment]
Possibly resolved with PR https://github.com/elimu-ai/appstore/pull/162

**Comment by jo-elimuai** [comment]
Crashes on Android 5.1.1 (API 22):

```
02-18 12:20:31.278 18570-18570/ai.elimu.appstore.debug I/AppListAdapter: fileName: com.ubongokids.ratmathEng-20160517.apk
02-18 12:20:31.279 18570-18570/ai.elimu.appstore.debug I/AppListAdapter: Downloading APK: com.ubongokids.ratmathEng (version 20160517, 69438kB)
02-18 12:20:31.337 18570-18719/ai.elimu.appstore.debug W/IonConscrypt: Conscrypt initialization failed.
                                                                       java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/security/ProviderInstaller;
                                                                           at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:58)
                                                                           at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:75)
                                                                           at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.getSocket(ConscryptMiddleware.java:103)
                                                                           at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:301)
                                                                           at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:51)
                                                                           at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:190)
                                                                           at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740)
                                                                           at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758)
                                                                           at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
                                                                           at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                                           at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
                                                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.security.ProviderInstaller" on path: DexPathList[[zip file "/data/app/ai.elimu.appstore.debug-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                           at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:58) 
                                                                           at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.initialize(ConscryptMiddleware.java:75) 
                                                                           at com.koushikdutta.ion.conscrypt.ConscryptMiddleware.getSocket(ConscryptMiddleware.java:103) 
                                                                           at com.koushikdutta.async.http.AsyncHttpClient.executeAffinity(AsyncHttpClient.java:301) 
                                                                           at com.koushikdutta.async.http.AsyncHttpClient.access$100(AsyncHttpClient.java:51) 
                                                                           at com.koushikdutta.async.http.AsyncHttpClient$1.run(AsyncHttpClient.java:190) 
                                                                           at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:740) 
                                                                           at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:758) 
                                                                           at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658) 
                                                                           at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44) 
                                                                           at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600) 
                                                                       	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.security.ProviderInstaller
                                                                           at java.lang.Class.classForName(Native Method)
                                                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                           		... 12 more
                                                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
02-18 12:20:43.401 18570-18570/ai.elimu.appstore.debug I/AppListAdapter: Download completed.
02-18 12:20:43.402 18570-18719/ai.elimu.appstore.debug I/System.out: handler: null
02-18 12:20:43.402 18570-18719/ai.elimu.appstore.debug I/System.out: emitter: HTTP/1.1 200 OK
02-18 12:20:43.402 18570-18719/ai.elimu.appstore.debug I/System.out: Date: Sun, 18 Feb 2018 11:20:30 GMT
02-18 12:20:43.402 18570-18719/ai.elimu.appstore.debug I/System.out: Set-Cookie: JSESSIONID=28th02jbs4io1tllfit0yu668;Path=/
02-18 12:20:43.402 18570-18719/ai.elimu.appstore.debug I/System.out: Expires: Thu, 01 Jan 1970 00:00:00 GMT
02-18 12:20:43.402 18570-18719/ai.elimu.appstore.debug I/System.out: Content-Type: application/octet-stream
02-18 12:20:43.402 18570-18719/ai.elimu.appstore.debug I/System.out: Content-Length: 71104830
02-18 12:20:43.403 18570-18570/ai.elimu.appstore.debug D/AppListAdapter: java.io.FileNotFoundException: /storage/emulated/0/.elimu-ai/appstore/apks/en/com.ubongokids.ratmathEng-20160517.apk: open failed: ENOENT (No such file or directory)
                                                                             at libcore.io.IoBridge.open(IoBridge.java:456)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
                                                                             at com.koushikdutta.async.stream.FileDataSink.getOutputStream(FileDataSink.java:24)
                                                                             at com.koushikdutta.async.stream.OutputStreamDataSink.write(OutputStreamDataSink.java:50)
                                                                             at com.koushikdutta.async.Util$3.onDataAvailable(Util.java:127)
                                                                             at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                             at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                                             at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                             at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                                             at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:385)
                                                                             at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                             at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56)
                                                                             at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33)
                                                                             at com.koushikdutta.async.Util.emitAllData(Util.java:23)
                                                                             at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
                                                                             at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821)
                                                                             at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658)
                                                                             at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44)
                                                                             at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600)
                                                                          Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                             at libcore.io.Posix.open(Native Method)
                                                                             at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                             at libcore.io.IoBridge.open(IoBridge.java:442)
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
                                                                             at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
                                                                             at com.koushikdutta.async.stream.FileDataSink.getOutputStream(FileDataSink.java:24) 
                                                                             at com.koushikdutta.async.stream.OutputStreamDataSink.write(OutputStreamDataSink.java:50) 
                                                                             at com.koushikdutta.async.Util$3.onDataAvailable(Util.java:127) 
                                                                             at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
                                                                             at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56) 
                                                                             at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
                                                                             at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56) 
                                                                             at com.koushikdutta.async.http.cache.ResponseCacheMiddleware$BodyCacher.onDataAvailable(ResponseCacheMiddleware.java:385) 
                                                                             at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
                                                                             at com.koushikdutta.async.FilteredDataEmitter.onDataAvailable(FilteredDataEmitter.java:56) 
                                                                             at com.koushikdutta.async.http.filter.ContentLengthFilter.onDataAvailable(ContentLengthFilter.java:33) 
                                                                             at com.koushikdutta.async.Util.emitAllData(Util.java:23) 
                                                                             at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152) 
                                                                             at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:821) 
                                                                             at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:658) 
                                                                             at com.koushikdutta.async.AsyncServer.access$800(AsyncServer.java:44) 
                                                                             at com.koushikdutta.async.AsyncServer$14.run(AsyncServer.java:600) 
02-18 12:20:43.412 18570-18570/ai.elimu.appstore.debug W/asset: Asset path /storage/emulated/0/.elimu-ai/appstore/apks/en/com.ubongokids.ratmathEng-20160517.apk is neither a directory nor file (type=1).
02-18 12:20:43.413 18570-18570/ai.elimu.appstore.debug D/AppListAdapter: 0.0 MB/67.8 MB	0%
```

**Comment by bojanvu23** [comment]
Hi,
Sorry for interrupting but I checked it now, and there is a problem with heap in the code:
`ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
byte[] buffer = new byte[1024];
int bytesRead = 0;
while ((bytesRead = inputStream.read(buffer)) != -1) {
	byteArrayOutputStream.write(buffer, 0, bytesRead);

	fileSizeInKbsDownloaded += (bytesRead / 1024);

	//Only update APK size every 100KB downloaded
	if (fileSizeInKbsDownloaded % 100 == 0) {
		publishProgress(fileSizeInKbsDownloaded);
	}
}
byte[] bytes = byteArrayOutputStream.toByteArray();

fileOutputStream = new FileOutputStream(apkFile);
fileOutputStream.write(bytes);
fileOutputStream.flush();`
because it add all data from file to variable(bytes) and then put them into file.
And because heap is limited the app crashes.

Instead it the data should put into the file in every iteration, for example:
`FileOutputStream fileOutputStream = new FileOutputStream(apkFile);
byte[] buffer = new byte[1024];
int bytesRead = 0;
while ((bytesRead = inputStream.read(buffer)) != -1) {
	fileOutputStream.write(buffer, 0, bytesRead);
	fileOutputStream.flush();                    
	
}`
here buffer can be set to 4096.
This works in Java, I will test in Android in few day if there would be need.

Bojan

**Comment by tuancoltech** [comment]
Hi Bojan,

The code snippet you posted is no longer used.
Kindly test with master branch.

Thanks.

**Comment by bojanvu23** [comment]
Hi  Tuan,

I just checked, I'm will test in few days.

btw how to obtain licence number for test, I wasn't on project from a long time I didn't have time so...I c
